import Head from 'next/head'
import Footer from '../components/Footer'
import Navbar from '../components/Navbar'
import Contact from './contact'
import HomePage from './homePage'
import Project from './project'
import Services from './services'
import Work from './work'

export default function Home() {
  return (
    <div >
      <Head>
        <title>ImBeen</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Navbar/>
      <HomePage/>
      <Services/>
      <Project/>
      <Work/>
      {/* <Contact/> */}
      <Footer/>
    </div>
  )
}
